services:
  open-webui:
    environment:
      WHISPER_MODEL: ${WHISPER_MODEL}  # Whisper model for OpenAI Edge TTS
      AUDIO_TTS_ENGINE: ${AUDIO_TTS_ENGINE}  # Text-to-Speech engine for OpenAI Edge TTS
      AUDIO_TTS_OPENAI_API_BASE_URL: ${AUDIO_TTS_OPENAI_API_BASE_URL}  # OpenAI Edge TTS API URL
      AUDIO_TTS_OPENAI_API_KEY: ${AUDIO_TTS_OPENAI_API_KEY}  # API key for OpenAI Edge TTS
      AUDIO_TTS_VOICE: ${AUDIO_TTS_VOICE}  # Voice for OpenAI Edge TTS
