services:
  open-webui-workspace:
    container_name: open-webui-workspace
    build: .
    working_dir: /workspace/open-webui-stack
    volumes:
      - open-webui-workspace:/workspace/open-webui-stack
      - /var/run/docker.sock:/var/run/docker.sock #optional
    networks: 
      - open-webui-workspace-network

volumes:
  open-webui-workspace:
    name: open-webui-workspace

networks: 
  open-webui-workspace-network:
    name: open-webui-workspace-network
