services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OPENAI_API_BASE_URL=$OPENAI_API_BASE_URL
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - TASK_MODEL_EXTERNAL=google/gemini-2.5-pro-exp-03-25:free
      - DEFAULT_MODELS=gemini-2.5-pro-exp-03-25:free
      - DEFAULT_LOCALE=ru
      - ENABLE_EVALUATION_ARENA_MODELS=False
      - ENABLE_OLLAMA_API=False
      - "WEBUI_SECRET_KEY=B7qrb5MN9NOknfeKcwwO2Q=="
    networks:
      - open-webui-network

volumes:
  open-webui:
    name: open-webui

networks:
  open-webui-network:
        name: open-webui-network
