services:
  open-webui:
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${OPENWEBUI_HOST}
      LETSENCRYPT_HOST: ${OPENWEBUI_HOST}
      LETSENCRYPT_EMAIL: ${OPENWEBUI_EMAIL}
    networks:
      - cert-network

networks:
  cert-network:
    external: true
