services:
  openai-edge-tts:
    image: travisvn/openai-edge-tts
    container_name: openai-edge-tts
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    environment:
      TZ: ${TZ:-UTC}
      API_KEY: ${API_KEY:-your_api_key_here}
      PORT: ${PORT:-5050}
      DEFAULT_VOICE: ${DEFAULT_VOICE:-ru-RU-DmitryNeural}
      DEFAULT_RESPONSE_FORMAT: ${DEFAULT_RESPONSE_FORMAT:-mp3}
      DEFAULT_SPEED: ${DEFAULT_SPEED:-1.0}
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-ru-RU}
      REQUIRE_API_KEY: ${REQUIRE_API_KEY:-True}
      REMOVE_FILTER: ${REMOVE_FILTER:-False}
      EXPAND_API: ${EXPAND_API:-True}
    networks:
      - open-webui-network

networks:
  open-webui-network:
    external: true
