services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-main}
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - open-webui:/app/backend/data
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    environment:
      OPENAI_API_BASE_URL: ${OPENAI_API_BASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TASK_MODEL_EXTERNAL: ${TASK_MODEL_EXTERNAL}
      DEFAULT_MODELS: ${DEFAULT_MODELS}
      DEFAULT_LOCALE: ${DEFAULT_LOCALE}
      ENABLE_EVALUATION_ARENA_MODELS: ${ENABLE_EVALUATION_ARENA_MODELS}
      ENABLE_OLLAMA_API: ${ENABLE_OLLAMA_API}
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
    networks:
      - open-webui-network

volumes:
  open-webui:
    name: open-webui

networks:
  open-webui-network:
    name: open-webui-network
